=begin
#Gitea API.

#This documentation describes the Gitea API.

The version of the OpenAPI document: {{AppVer | JSEscape | Safe}}

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module GiteaRubyClient
  # MergePullRequestForm form for merging Pull Request
  class MergePullRequestOption
    attr_accessor :_do

    attr_accessor :merge_commit_id

    attr_accessor :merge_message_field

    attr_accessor :merge_title_field

    attr_accessor :delete_branch_after_merge

    attr_accessor :force_merge

    attr_accessor :head_commit_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_do' => :'Do',
        :'merge_commit_id' => :'MergeCommitID',
        :'merge_message_field' => :'MergeMessageField',
        :'merge_title_field' => :'MergeTitleField',
        :'delete_branch_after_merge' => :'delete_branch_after_merge',
        :'force_merge' => :'force_merge',
        :'head_commit_id' => :'head_commit_id'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_do' => :'String',
        :'merge_commit_id' => :'String',
        :'merge_message_field' => :'String',
        :'merge_title_field' => :'String',
        :'delete_branch_after_merge' => :'Boolean',
        :'force_merge' => :'Boolean',
        :'head_commit_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GiteaRubyClient::MergePullRequestOption` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GiteaRubyClient::MergePullRequestOption`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_do')
        self._do = attributes[:'_do']
      end

      if attributes.key?(:'merge_commit_id')
        self.merge_commit_id = attributes[:'merge_commit_id']
      end

      if attributes.key?(:'merge_message_field')
        self.merge_message_field = attributes[:'merge_message_field']
      end

      if attributes.key?(:'merge_title_field')
        self.merge_title_field = attributes[:'merge_title_field']
      end

      if attributes.key?(:'delete_branch_after_merge')
        self.delete_branch_after_merge = attributes[:'delete_branch_after_merge']
      end

      if attributes.key?(:'force_merge')
        self.force_merge = attributes[:'force_merge']
      end

      if attributes.key?(:'head_commit_id')
        self.head_commit_id = attributes[:'head_commit_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @_do.nil?
        invalid_properties.push('invalid value for "_do", _do cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @_do.nil?
      _do_validator = EnumAttributeValidator.new('String', ["merge", "rebase", "rebase-merge", "squash", "manually-merged"])
      return false unless _do_validator.valid?(@_do)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] _do Object to be assigned
    def _do=(_do)
      validator = EnumAttributeValidator.new('String', ["merge", "rebase", "rebase-merge", "squash", "manually-merged"])
      unless validator.valid?(_do)
        fail ArgumentError, "invalid value for \"_do\", must be one of #{validator.allowable_values}."
      end
      @_do = _do
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _do == o._do &&
          merge_commit_id == o.merge_commit_id &&
          merge_message_field == o.merge_message_field &&
          merge_title_field == o.merge_title_field &&
          delete_branch_after_merge == o.delete_branch_after_merge &&
          force_merge == o.force_merge &&
          head_commit_id == o.head_commit_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_do, merge_commit_id, merge_message_field, merge_title_field, delete_branch_after_merge, force_merge, head_commit_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = GiteaRubyClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
