=begin
#Gitea API.

#This documentation describes the Gitea API.

The version of the OpenAPI document: {{AppVer | JSEscape | Safe}}

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GiteaRubyClient::CreateOAuth2ApplicationOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GiteaRubyClient::CreateOAuth2ApplicationOptions do
  let(:instance) { GiteaRubyClient::CreateOAuth2ApplicationOptions.new }

  describe 'test an instance of CreateOAuth2ApplicationOptions' do
    it 'should create an instance of CreateOAuth2ApplicationOptions' do
      expect(instance).to be_instance_of(GiteaRubyClient::CreateOAuth2ApplicationOptions)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "redirect_uris"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
